name: Deploy Abbot Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    name: Build and deploy Abbot Docs

    steps:
    - name: Checkout docs repo
      uses: actions/checkout@v2
      with:
        repository: aseriousbiz/abbot-docs
        ref: main
        fetch-depth: 1
        path: abbot-docs

    - name: Checkout Abbot repo
      uses: actions/checkout@v2
      with:
        repository: aseriousbiz/abbot
        ref: main
        token: ${{ secrets.GH_PAT }}
        fetch-depth: 1
        path: abbot

    - uses: nikeee/docfx-action@v1.0.0
      name: Build Documentation
      with:
        args: abbot-docs/src/docfx.json

    # Publish generated site using GitHub Pages
    - uses: maxheld83/ghpages@master
      name: Publish Documentation on GitHub Pages
      env:
        BUILD_DIR: abbot-docs/_site # docfx's default output directory is _site
        GH_PAT: ${{ secrets.GH_PAT }} # See https://github.com/maxheld83/ghpages
      if: github.event_name != 'pull_request'